# Generated by Django 2.1 on 2018-08-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20180809_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64Image', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='base64image',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='images',
            name='imageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Picture'),
        ),
    ]
