# Generated by Django 2.1 on 2018-08-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20180810_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.BooleanField(default=False)),
                ('up_votes_balance_before', models.IntegerField()),
                ('up_votes_balance_after', models.IntegerField()),
                ('down_votes_balance_before', models.IntegerField()),
                ('down_votes_balance_after', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='picture_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user_id',
        ),
        migrations.AddField(
            model_name='picture',
            name='down_votes_account',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='up_votes_account',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='votinghistory',
            name='picture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Picture'),
        ),
        migrations.AddField(
            model_name='votinghistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.User'),
        ),
        migrations.AlterUniqueTogether(
            name='votinghistory',
            unique_together={('user_id', 'picture_id')},
        ),
    ]
