# Generated by Django 2.1 on 2018-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20180811_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinghistory',
            name='vote_type',
            field=models.NullBooleanField(),
        ),
    ]
