# Generated by Django 2.1 on 2018-08-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20180811_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='imageId',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='photos.Picture'),
        ),
    ]
