# Generated by Django 2.1 on 2018-08-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20180811_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Picture'),
        ),
    ]
