# Generated by Django 2.1 on 2018-08-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20180811_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='imageId',
        ),
    ]
