# Generated by Django 2.1 on 2018-08-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20180811_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='imageId',
            new_name='picture_details',
        ),
    ]
